Repository bobtail-soda/sport-app, pull requests merged in 2024-02, with the labels that each got.

#19 🐛 fetch data after update data in summary page
  src/pages/Exercise/CreateExercise/SummaryExercise.jsx
  src/pages/Exercise/EditExercise/EditExercise.jsx
Labels: bug

#25 Get api user profile data to show in dashboard
  public/images/default_avatar.png
  src/components/shared/Rightbar.jsx
Labels: api

#26 Integreted dashboard api
  src/components/CardSummary/CardSummary.jsx
  src/components/Charts/DonutChart.jsx
  src/components/Charts/LineChart.jsx
  src/components/Charts/PieChart.jsx
  src/components/shared/Rightbar.jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/User/List.jsx
Labels: api

#30 Modified filed name for match with api
  src/components/Charts/DonutChart.jsx
  src/components/Charts/LineChart.jsx
  src/pages/Exercise/CreateExercise/SummaryExercise.jsx
Labels: api

#31 Hot fix login ui
  src/pages/Authentication/Login/Login.jsx
Labels: bug

#33 Integrate forgot password api
  src/pages/Authentication/ForgotPassword/ForgotPassword.jsx
  src/pages/Authentication/Login/Login.jsx
Labels: api

#38 Integrated api Create New Password
  src/pages/Authentication/ForgotPassword/CreateNewPassword.jsx
  src/pages/Authentication/ForgotPassword/EmailVerification.jsx
  src/pages/Authentication/ForgotPassword/ForgotPassword.jsx
Labels: api

#41 Added distance and calulated calories & user id from localStorage
  src/components/CalculateCalories/CalculateCalories.jsx
  src/components/shared/Rightbar.jsx
  src/pages/Exercise/CreateExercise/SummaryExercise.jsx
  src/pages/Exercise/CreateExercise/TrackingExerciseForm.jsx
  src/pages/Login/LoginBackup.jsx
Labels: UI

#42 Get activity type data from api
  src/pages/Exercise/CreateExercise/SummaryExercise.jsx
  src/pages/Exercise/CreateExercise/TrackingExerciseForm.jsx
Labels: api

#43 Added hide/show password & Added loading logged in with SweetAlert
  src/pages/Authentication/Login/Login.jsx
Labels: UI

#53 Convert Format date
  package-lock.json
  package.json
  src/components/shared/Rightbar.jsx
  src/pages/Exercise/CreateExercise/SummaryExercise.jsx
  src/utils/formatDate.js
Labels: UI

#56 Get firstName, lastName, phone to show on rightbar
  src/components/shared/Rightbar.jsx
Labels: UI

#57 Validate form & show/hide password
  src/pages/Authentication/ForgotPassword/CreateNewPassword.jsx
Labels: bug

#59 Created Favorite activity type
  src/api/services/dashboard.js
  src/api/services/exerciseActivity.js
  src/components/CardSummary/CardSummary.jsx
  src/components/Charts/DonutChart.jsx
  src/components/shared/Rightbar.jsx
Labels: UI

#62 Hide Today date_range but will use in the future
  src/components/Charts/LineChart.jsx
  src/pages/Dashboard/Dashboard.jsx
Labels: bug

#64 Added Logout button & Show error message from api in login & Store email in localStorage
  src/components/shared/Navbar.jsx
  src/pages/Authentication/Login/Login.jsx
  src/pages/Authentication/SignUp/SignUp.jsx
Labels: UI

#65 Fixed bug logout & email verification
  src/api/services/auth.js
  src/components/shared/Navbar.jsx
  src/pages/ActivityType/Nav.jsx
  src/pages/Authentication/ForgotPassword/EmailVerification.jsx
Labels: bug
